### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by noloman** [remotive-io/remote-jobs-api#1]
Hi!

I can't see any documentation for the [tags endpoint](https://remotive.io/api/remote-jobs/tags). Is this on purpose?
I see the tags are not even included in the jobs when fetched from the `remote-jobs` endpoint, so I'm guessing it's either broken or not (yet?) implemented.

Are you guys planning on fixing this at some point? Thanks a lot for the hard work :)

**Comment by adriencombourieu** [comment]
Hi Manuel,

Thank you for your question,

Actually we are not doing tags anymore, this is deprecated.

We rather use search keywords instead.

I'll update the documentation if it's still referring to tags.

Cheers

Adrien

Le sam. 15 janv. 2022 à 12:23, Manuel Lorenzo ***@***.***> a
écrit :
