### ISSUE TITLE
URL endpoint for HTTP Request giving HTML as response.

### ISSUE THREAD

**Issue by himanshumistri** [remotive-io/remote-jobs-api#12]
I wonder, When i hit get API using ktor client.

`Response is <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function()...`

It gives me the HTML page as a response instead of the original JSON Data. How to resolve this, Do i need an API key to use public API? If yes how to get it?

**Comment by adriencombourieu** [comment]
Hi there,
Please provide a full example to reproduce this. Ideally with curl.
What endpoint and request are you doing?
Best
Adrien

**Comment by himanshumistri** [comment]
Hey @adriencombourieu 
It's very simple just hit this URL with curl . https://remotive.com/api/remote-jobs

It's appears like due to Cloudflare security direct hit to API does not work , thus it give the HTML as response

See the attached screenshot.

<img width="1373" alt="Screenshot 2023-11-30 at 2 55 11 PM" src="https://github.com/remotive-com/remote-jobs-api/assets/745526/f4ee73dc-cee6-4463-bcdc-58da206d27b9">

**Comment by adriencombourieu** [comment]
Hi @himanshumistri 

Ok, please try again and let me know ?

Cheers

**Comment by himanshumistri** [comment]
Thanks, It's resolved now @adriencombourieu
