### ISSUE TITLE
Add `skip` optional parameter to enable client-side pagination

### ISSUE THREAD

**Issue by ahmed0saber** [remotive-io/remote-jobs-api#13]

**Comment by adriencombourieu** [comment]
Hi there,

Good point. Actually, it should already be available (even though not documented) with the 'offset' parameter:

https://remotive.com/api/remote-jobs?limit=10&offset=10

This would e.g. be used to display page 2 if paginated 10 by 10

Please let me know if it works, then I'll add it to the doc.

Thanks!

**Comment by ahmed0saber** [comment]
Hi @adriencombourieu ,

Yes, it works as expected.

Thanks for letting me know, but what about adding `pages_count` or `total_number_of_jobs` to the response?
With this addition, we can know which pages we can navigate to, instead of navigating to empty page by mistake, also in this way we can display how many pages are there and in which page we are now.

Thanks in advance!

**Comment by SayedGouse** [comment]
hi, @adriencombourieu .

Can you please send in response total number of jobs in  **job-count** not the number of limit also please remove hyphen ('-') in job-count just sent jobcount or something. It helps for pagination.

Thank you so much.

**Comment by adriencombourieu** [comment]
Hi, 
I added "total-job-count" with this info:

Example:
https://remotive.com/api/remote-jobs?category=data&limit=20

Now returns:
![image](https://github.com/user-attachments/assets/9e210a8a-589f-45d8-84a2-1e877cc0a8a4)

**Comment by adriencombourieu** [comment]
You can now compute page number / pagination on your frontend side, based on your limit/offset and response "total-job-count" here

**Comment by SayedGouse** [comment]
Thanks it works.
